"""DFDOF Phase 8 — PDF forensic baseline report builder.

Assembles all sections from state.json into a single PDF using fpdf2.
Figures are generated by reporting.plots and embedded as PNGs.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

from fpdf import FPDF

from config import (
    DRONE_LOGS,
    FLIGHT_RECORDS,
    SOURCE_IDENTIFICATION_TYPES,
    CONTROLLER_ARTEFACT_CATEGORIES,
)
from phases.p7_analysis_and_validation import _P4_IDENTITY_FIELDS, _P4_KEY_TO_OUT_KEY
from reporting.plots import plot_drone_log, plot_flight_record, plot_flight_track
from state import State

# Layout constants

_FONT    = "Helvetica"
_MARGIN_L = 15
_MARGIN_R = 15
_MARGIN_T = 22   # extra top margin so header text never overlaps section titles
_PAGE_W   = 210  # A4 mm
_USABLE_W = _PAGE_W - _MARGIN_L - _MARGIN_R  # 180 mm
_LINE_H   = 4.5  # compact body line height


# PDF class

class _PDF(FPDF):
    def __init__(self, case_id: str) -> None:
        super().__init__(orientation="P", unit="mm", format="A4")
        self._case_id = case_id
        self.set_margins(_MARGIN_L, _MARGIN_T, _MARGIN_R)
        self.set_auto_page_break(auto=True, margin=18)

    def header(self) -> None:
        if self.page_no() == 1:
            return
        self.set_font(_FONT, "", 9)
        self.set_text_color(160, 160, 160)
        self.set_y(8)
        self.cell(0, 4, _safe(f"DFDOF Forensic Baseline Report  |  {self._case_id}"), align="R")
        self.set_text_color(0, 0, 0)
        self.set_y(_MARGIN_T)

    def footer(self) -> None:
        self.set_y(-12)
        self.set_font(_FONT, "", 7)
        self.set_text_color(160, 160, 160)
        self.cell(0, 4, f"Page {self.page_no()}  |  NOT FOR COURT USE", align="C")
        self.set_text_color(0, 0, 0)


# Public entry point

def build_report(state: State, output_path: Path, plots_dir: Path) -> None:
    """Assemble the complete PDF and write it to output_path."""
    pdf = _PDF(state.case_id)
    p7  = state.phase_outputs.get("p7_analysis_and_validation", {})

    _cover_page(pdf, state)
    _chain_of_custody(pdf, state)
    _pipeline_summary(pdf, state, p7)
    _device_identification(pdf, p7)

    p6_flights     = state.phase_outputs.get("p6_multisource_correlation", {}).get("flights", [])
    flight_analyses = p7.get("flight_analyses", [])
    fa_by_id        = {fa["flight_id"]: fa for fa in flight_analyses}

    for flight in p6_flights:
        fid = flight["flight_id"]
        fa  = fa_by_id.get(fid, {})
        _flight_section(pdf, state, flight, fa, plots_dir)

    _artefact_coverage(pdf, p7)
    _data_quality(pdf, p7, state)
    _further_investigation(pdf, p7)
    _appendix_hashes(pdf, state)
    _appendix_lineage(pdf, state)
    _appendix_tool_log(pdf, state)
    _appendix_tool_overview(pdf)

    pdf.output(str(output_path))


# Sections

def _cover_page(pdf: _PDF, state: State) -> None:
    pdf.add_page()
    pdf.ln(10)
    # Logo — centred, 40 mm wide
    logo = Path(__file__).parent.parent / "LOGO.png"
    if logo.exists():
        logo_w = 65
        pdf.image(str(logo), x=(_PAGE_W - logo_w) / 2, w=logo_w)
        pdf.ln(6)
    else:
        pdf.ln(16)
    pdf.set_font(_FONT, "B", 22)
    pdf.cell(0, 12, "Forensic Baseline Report", align="C")
    pdf.ln(8)
    pdf.set_font(_FONT, "B", 14)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 8, "Drone Forensic Decision and Orchestration Framework", align="C")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(14)

    # Key-value metadata block — fixed column widths so everything aligns
    label_w = 48
    value_w = _USABLE_W - label_w
    rows = [
        ("Case Identifier",   state.case_id),
        ("Operator",          state.operator),
        ("Analysis Started",  (state.start_time or "")[:19].replace("T", " ")),
        ("Evidence Directory", str(state.evidence_directory or "-")),
        ("Output Directory",  str(Path(state.evidence_directory or "").parent / "dfdof_output" / state.case_id)),
        ("Evidence Sources",  str(len(state.input_evidence))),
        ("Pipeline Version",  "DFDOF v1.0 (proof of concept)"),
    ]
    for label, value in rows:
        pdf.set_x(_MARGIN_L)
        pdf.set_font(_FONT, "B", 10)
        pdf.cell(label_w, 6, _safe(label + ":"))
        pdf.set_x(_MARGIN_L + label_w)
        pdf.set_font(_FONT, "", 10)
        pdf.multi_cell(value_w, 6, _safe(value))

    pdf.ln(10)
    pdf.set_x(_MARGIN_L)
    pdf.set_font(_FONT, "I", 8)
    pdf.set_text_color(130, 130, 130)
    pdf.multi_cell(_USABLE_W, _LINE_H, _safe(
        "This report is an automated forensic baseline produced by DFDOF. "
        "It is not a court-ready expert report. All findings are bounded by the "
        "data available and must be interpreted by a qualified forensic examiner."
    ), align="C")
    pdf.set_text_color(0, 0, 0)


def _chain_of_custody(pdf: _PDF, state: State) -> None:
    pdf.add_page()
    _section_title(pdf, "1. Evidence Intake and Chain of Custody")
    _body_text(pdf,
        "The following input evidence files were ingested. SHA-256 and SHA-1 "
        "hashes were computed at intake to establish integrity baselines. "
        "No modification to original evidence files is performed by DFDOF."
    )
    pdf.ln(2)

    headers = ["File", "Classification", "Acquisition", "Size", "Hash Timestamp"]
    col_w   = [52, 32, 26, 22, 48]
    rows = []
    for ev in state.input_evidence:
        rows.append([
            Path(str(ev.source_path)).name,
            ev.source_identification or "-",
            ev.acquisition_method or "-",
            _format_size(ev.size),
            (ev.hash_timestamp or "-")[:19].replace("T", " "),
        ])
    _table(pdf, headers, rows, col_w)
    pdf.ln(4)

    # Input path
    _subsection_title(pdf, "Evidence Source Path")
    _body_text(pdf, str(state.evidence_directory or "-"))
    pdf.ln(2)

    # Full hash table — one self-contained block per file
    _subsection_title(pdf, "Cryptographic Hashes")

    row_h   = 5
    fname_w = 90   # filename column
    src_w   = 50   # classification column
    meth_w  = _USABLE_W - fname_w - src_w  # 40 mm — acquisition method
    label_w = 22   # "SHA-256:" / "SHA-1:" label column
    hash_w  = _USABLE_W - label_w  # 158 mm — wide enough for 64-char Courier 7pt

    for ev in state.input_evidence:
        fname  = Path(str(ev.source_path)).name
        source = ev.source_identification or "-"
        method = ev.acquisition_method or "-"
        sha256 = ev.sha256 or "not computed"
        sha1   = ev.sha1   or "not computed"

        # Row 1 — file metadata strip (dark-blue header): three separate columns
        pdf.set_font(_FONT, "B", 8)
        pdf.set_fill_color(50, 80, 130)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(fname_w, row_h, _safe(fname),   border=1, fill=True)
        pdf.cell(src_w,   row_h, _safe(source),  border=1, fill=True)
        pdf.cell(meth_w,  row_h, _safe(method),  border=1, fill=True)
        pdf.ln()
        pdf.set_text_color(0, 0, 0)

        # Row 2 — SHA-256
        pdf.set_fill_color(250, 250, 252)
        pdf.set_font(_FONT, "B", 8)
        pdf.cell(label_w, row_h, "SHA-256:", border=1, fill=True)
        pdf.set_font("Courier", "", 7)
        pdf.cell(hash_w, row_h, _safe(sha256), border=1, fill=True)
        pdf.ln()

        # Row 3 — SHA-1
        pdf.set_fill_color(250, 250, 252)
        pdf.set_font(_FONT, "B", 8)
        pdf.cell(label_w, row_h, "SHA-1:", border=1, fill=True)
        pdf.set_font("Courier", "", 7)
        pdf.cell(hash_w, row_h, _safe(sha1), border=1, fill=True)
        pdf.ln(5)


def _pipeline_summary(pdf: _PDF, state: State, p7: dict) -> None:
    pdf.add_page()
    _section_title(pdf, "2. Pipeline Execution Summary")

    # Completed phases as numbered list
    _subsection_title(pdf, "Completed Phases")
    phases = state.completed_phases or []
    if not phases:
        _body_text(pdf, "None recorded.")
    else:
        for i, phase in enumerate(phases, 1):
            _numbered(pdf, i, phase)
    pdf.ln(4)

    # Anomaly flags
    _subsection_title(pdf, "Anomaly Flags")
    flags = state.anomaly_flags or []
    if not flags:
        _body_text(pdf, "No anomalies recorded.")
    else:
        for i, flag in enumerate(flags, 1):
            _numbered(pdf, i, flag)
    pdf.ln(4)

    # Tool status
    _subsection_title(pdf, "Tool Execution Status")
    tool_status = p7.get("tool_status", [])
    if not tool_status:
        _body_text(pdf, "No tool invocations recorded.")
    else:
        headers = ["Tool", "Invocations", "Successes", "Status"]
        col_w   = [50, 30, 30, 40]
        rows = [
            [t["tool"], str(t["invocation_count"]), str(t["success_count"]),
             _status_badge(t["status"])]
            for t in tool_status
        ]
        _table(pdf, headers, rows, col_w)


def _device_identification(pdf: _PDF, p7: dict) -> None:
    pdf.add_page()
    _section_title(pdf, "3. Device and Account Identification")

    ada = p7.get("account_and_drone_analysis", {})
    if not ada:
        _body_text(pdf, "No device or account information could be extracted.")
        return

    # Registry-driven: rows are built from _P4_IDENTITY_FIELDS plus the two P2-only keys.
    # Adding a field to a P4 field-map dict automatically appears here.
    _REPORT_FIELDS: tuple[tuple[str, str], ...] = (
        ("installed_dji_apps", "Installed DJI App(s)"),
        ("device_name",        "Controller Device"),
    ) + tuple(
        (_P4_KEY_TO_OUT_KEY.get(p4k, p4k), label)
        for p4k, label in _P4_IDENTITY_FIELDS
    )
    headers = ["Field", "Value", "Confidence", "Sources"]
    col_w   = [48, 62, 38, 22]  # sum = 170 < 180 OK
    rows = []
    for key, label in _REPORT_FIELDS:
        entry = ada.get(key)
        if not entry:
            continue
        val = entry.get("value", "-")
        if isinstance(val, list):
            val = "\n".join(str(v) for v in val)
        rows.append([
            label,
            str(val),
            _confidence_badge(entry.get("confidence", "")),
            str(len(entry.get("corroboration_sources", []))),
        ])
    if rows:
        _table(pdf, headers, rows, col_w)
    pdf.ln(4)

    _subsection_title(pdf, "Processing Coverage Score")
    cov = p7.get("coverage_score", {})
    score_items = [
        ("Evidence Sources Detected",        "evidence_sources_detected"),
        ("Artefact Categories With Data",    "artefact_categories_with_data"),
        ("Flights With Primary Correlation", "flights_with_primary_correlation"),
        ("Tools Succeeded",                  "tools_succeeded"),
    ]
    headers2 = ["Metric", "Result"]
    col_w2   = [130, 30]
    rows2 = []
    for label, key in score_items:
        v = cov.get(key, {})
        rows2.append([label, f"{v.get('value', '?')} / {v.get('total', '?')}"])
    _table(pdf, headers2, rows2, col_w2)


def _flight_section(
    pdf: _PDF,
    state: State,
    flight: dict,
    fa: dict,
    tmp_dir: Path,
) -> None:
    pdf.add_page()
    fid     = flight["flight_id"]
    corr    = flight.get("correlation", {})
    matched = corr.get("matched", False)

    _section_title(pdf, f"4. Flight Analysis - {fid.replace('_', ' ').title()}")

    # Correlation and flight window
    _subsection_title(pdf, "Correlation and Flight Window")
    status = "Matched (primary GPS+temporal)" if matched else "Unmatched (no drone log corroboration)"
    _kv(pdf, "Status", status)
    if matched:
        _kv(pdf, "Confidence",          str(corr.get("confidence", "-")))
        _kv(pdf, "GPS Overlap",         f"{corr.get('overlap_s', '-')} s")
        _kv(pdf, "Median GPS Distance", f"{corr.get('median_distance_m', '-')} m")
        _raw = corr.get("overlap_fraction")
        _overlap_pct = f"{int(_raw * 100)}%" if isinstance(_raw, (int, float)) else "-"
        _kv(pdf, "Overlap",             _overlap_pct)
        _mr = corr.get("match_rate")
        _mr_pct = f"{int(_mr * 100)}%" if isinstance(_mr, (int, float)) else "-"
        _kv(pdf, "GPS Match Rate",      _mr_pct)

    # Build sha → category lookup from P5 normalised artefacts
    _p5_artefacts = (
        state.phase_outputs
        .get("p5_normalisation_and_anomaly_checking", {})
        .get("normalised_artefacts", [])
    )
    _sha_to_cat = {a.get("sha256", ""): a.get("artefact_category", "") for a in _p5_artefacts}
    _sha_to_source = {a.get("sha256", ""): a.get("source_identification", "-") for a in _p5_artefacts}

    _cat_labels = {
        FLIGHT_RECORDS: "Flight Record",
        DRONE_LOGS:     "Drone Log",
    }

    fi = flight.get("flights_identified", [])
    for seg in fi:
        sha = seg.get("evidence_sha256") or "-"
        cat = _sha_to_cat.get(sha, "")
        label = _cat_labels.get(cat, "Source")
        _kv_hash(pdf, f"{label} SHA-256", sha)
        _kv(pdf, "Start",    seg.get("start", "-"))
        _kv(pdf, "End",      seg.get("end",   "-"))
        _kv(pdf, "Duration", f"{seg.get('duration_s', '-')} s")
    pdf.ln(3)

    # Flight metrics
    if fa:
        _subsection_title(pdf, "Flight Metrics")
        _kv(pdf, "Peak Height",        f"{fa.get('peak_height_m')} m" if fa.get('peak_height_m') else "-")
        _kv(pdf, "Distance Travelled", f"{fa.get('distance_travelled')} m" if fa.get('distance_travelled') else "-")
        _kv(pdf, "Video Recording",    "Yes" if fa.get("video_taken") else "No")
        _kv(pdf, "Photo Capture",      "Yes" if fa.get("photo_taken") else "No")
        if fa.get("number_photos_taken") is not None:
            _kv(pdf, "Photos Taken",      str(fa["number_photos_taken"]))
        if fa.get("duration_recording") is not None:
            _kv(pdf, "Recording Duration", f"{fa['duration_recording']} s")
        if fa.get("flight_record_complete") is not None:
            complete = "Yes" if fa["flight_record_complete"] else "No - drone had not returned to home point"
            _kv(pdf, "Record Complete", complete)
        pdf.ln(3)

    # Key events table
    tl_path = flight.get("stored_path", "")
    events  = _load_timeline_events(tl_path)

    key_event_types = {
        "Log started", "Log ended", "Motor turned on", "Motor turned off",
        "Reached peak height", "Record mode changed",
    }
    photo_events = [
        e for e in events
        if e.get("event") == "Photo mode changed"
        and str(e.get("data", {}).get("photo_mode", "No")).lower() not in ("no", "")
    ]
    key_events = [e for e in events if e.get("event") in key_event_types] + photo_events

    # Fly modes — numbered chronological list
    modes_seen: list[str] = []
    seen_set:   set[str]  = set()
    for e in events:
        if e.get("event") == "Fly mode changed":
            m = e.get("data", {}).get("fly_mode", "")
            if m and m not in seen_set:
                modes_seen.append(m)
                seen_set.add(m)
    if modes_seen:
        _subsection_title(pdf, "Fly Modes Observed (Chronological)")
        for i, mode in enumerate(modes_seen, 1):
            _numbered(pdf, i, mode)
        pdf.ln(3)

    if key_events:
        _subsection_title(pdf, "Key Events")
        headers = ["Timestamp (UTC)", "Source", "Event", "Details"]
        col_w   = [40, 35, 35, 60]
        rows = []
        for ev in key_events:
            ts  = (ev.get("timestamp") or "-")[:19].replace("T", " ")
            src = _short_source(ev.get("source", ""))
            evt = ev.get("event", "")
            det = _event_detail(ev)
            rows.append([ts, src, evt, det])
        _table(pdf, headers, rows, col_w)
    else:
        _body_text(pdf, "No key events extracted from timeline.")
    pdf.ln(3)

    # Warnings
    warnings = [
        e for e in events
        if e.get("event") == "Log message"
        and "Warning" in str(e.get("data", {}).get("log_message", ""))
    ]
    if warnings:
        _subsection_title(pdf, "In-Flight Warnings")
        headers = ["Timestamp (UTC)", "Source", "Warning Message"]
        col_w   = [40, 35, 95]
        rows = []
        for ev in warnings[:30]:
            ts  = (ev.get("timestamp") or "-")[:19].replace("T", " ")
            src = _short_source(ev.get("source", ""))
            msg = str(ev.get("data", {}).get("log_message", ""))[:160]
            rows.append([ts, src, msg])
        _table(pdf, headers, rows, col_w)
        pdf.ln(3)

    # Correlation tables
    plausible = flight.get("plausibly_correlated", [])
    possible  = flight.get("possibly_correlated",  [])
    if plausible or possible:
        _subsection_title(pdf, "Correlated Artefacts")
        if plausible:
            _body_text(pdf, "Plausibly correlated (timestamp within flight window):")
            rows = []
            for ptr in plausible:
                sha = ptr.removeprefix("p5:").removeprefix("p4:")
                source = _sha_to_source.get(sha, "-")
                rows.append([_safe(source), _safe(ptr)])
            _table(pdf, ["Source", "Pointer"], rows, [60, 120])
        if possible:
            _body_text(pdf, "Possibly correlated (indirect indicators):")
            for pc in possible:
                source  = _safe(str(pc.get("source", "-")))
                basis   = _safe(_format_basis(pc.get("data", {})))
                pointer = _safe(str(pc.get("source_pointer", "-")))
                _corr_row(pdf, [source, basis], [60, 120], (50, 80, 130),
                          text_rgb=(255, 255, 255), bold=True)
                _corr_row(pdf, [pointer],       [180],     (255, 255, 255))
                pdf.ln(2)
        pdf.ln(3)

    # ── Sensor plots — each on its own page ──────────────────────────────────
    fr_csv, dl_csv = _flight_csv_paths(state, flight)

    fr_png = plot_flight_record(fr_csv, events, fid, tmp_dir) if fr_csv else None
    dl_png = plot_drone_log(dl_csv, fid, tmp_dir)             if dl_csv else None

    if fr_png:
        pdf.add_page()
        _subsection_title(pdf, "Flight Record - Sensor Telemetry")
        _embed_image(pdf, fr_png, w=175)
        pdf.ln(2)
        pdf.set_font(_FONT, "I", 7)
        pdf.set_text_color(120, 120, 120)
        pdf.multi_cell(_USABLE_W, _LINE_H, _safe(
            "GPS coordinates are derived from the drone's onboard receiver and represent "
            "sensor-recorded positions, not independently verified measurements. "
            "A satellite count of 10 or more is associated with good horizontal precision "
            "(approximately 1.5-3 m); counts below 4 indicate a poor fix with significantly "
            "reduced positional reliability, and those rows are flagged in this report. "
            "Low satellite counts may affect the accuracy of the flight path, ground track, "
            "and any location-based conclusions drawn from this record."
        ))
        pdf.set_text_color(0, 0, 0)
    elif not fr_csv:
        pass  # no flight record available — silent
    else:
        _body_text(pdf, "Flight record sensor plots not available.")

    if dl_png:
        pdf.add_page()
        _subsection_title(pdf, "Drone Log - Sensor Telemetry")
        _embed_image(pdf, dl_png, w=175)
        pdf.ln(2)
        pdf.set_font(_FONT, "I", 7)
        pdf.set_text_color(120, 120, 120)
        pdf.multi_cell(_USABLE_W, _LINE_H, _safe(
            "GPS coordinates are derived from the drone's onboard receiver; horizontal accuracy "
            "is subject to satellite geometry (hDOP) and signal environment, with DJI manufacturer "
            "specification of +/-1.5 m horizontal in GPS mode. "
            "An hDOP below 1.5 is considered very precise, while values above 5.0 indicate "
            "degraded positional accuracy - those records are flagged and should be treated with "
            "reduced confidence in derived locations and ground track. "
            "Bayesian likelihood ratio analysis for a specific location hypothesis is possible "
            "using a Gaussian error model parameterised by hDOP, but requires case-specific "
            "inputs and is outside the scope of this baseline report."
        ))
        pdf.set_text_color(0, 0, 0)

    # ── Flight track ──────────────────────────────────────────────────────────
    kml       = _find_kml_path(state)
    track_png = None
    if fr_csv or dl_csv:
        track_png = plot_flight_track(fr_csv, dl_csv, kml, fid, tmp_dir)
    if track_png:
        pdf.add_page()
        _subsection_title(pdf, "Flight Ground Track")
        # Constrain by height so tall stacked plots stay on one page with the header.
        # A4 usable height minus top margin, subsection title, and caption ≈ 220 mm.
        _track_max_h = 220
        _track_w     = int(_USABLE_W * 0.80)   # 20 % smaller than full usable width
        try:
            x = (_PAGE_W - _track_w) / 2
            pdf.image(str(track_png), x=x, w=_track_w, h=_track_max_h)
        except Exception:
            _body_text(pdf, "[Flight track image could not be embedded.]")
        pdf.ln(2)
        pdf.set_font(_FONT, "I", 7)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(0, 4, "Coordinates are WGS84. No base map. Colour represents relative height (metres).")
        pdf.ln(4)
        if kml and kml.exists():
            pdf.set_font(_FONT, "I", 7)
            pdf.set_text_color(120, 120, 120)
            pdf.multi_cell(_USABLE_W, _LINE_H, _safe(
                f"A KML file ({kml.name}) is available in the output directory and may be loaded into "
                "Google Earth Pro for 3D visualisation of the flight path. Note: loading this file into "
                "an external application constitutes forensic evidence disclosure — ensure this is "
                "authorised before doing so."
            ))
        pdf.set_text_color(0, 0, 0)
    else:
        _body_text(pdf, "Flight track plot not available.")


def _artefact_coverage(pdf: _PDF, p7: dict) -> None:
    pdf.add_page()
    _section_title(pdf, "5. Artefact Coverage")

    _subsection_title(pdf, "Source Coverage")
    sc = p7.get("source_coverage", [])
    if sc:
        headers = ["Source", "Detected"]
        col_w   = [120, 40]
        rows = [[s["source"], "Yes" if s["detected"] else "No"] for s in sc]
        _table(pdf, headers, rows, col_w)
    pdf.ln(4)

    _subsection_title(pdf, "Artefact Counts per Source and Category")
    per_src = p7.get("artefact_coverage_per_source", [])
    if per_src:
        all_cats = list(CONTROLLER_ARTEFACT_CATEGORIES)
        src_col_w = 30
        num_w = max(21, int((_USABLE_W - src_col_w) / len(all_cats)))
        headers = ["Source"] + [c.replace("_", " ").title() for c in all_cats]
        col_w   = [src_col_w] + [num_w] * len(all_cats)
        rows = []
        for src_entry in per_src:
            cat_counts = {a["category"]: a["count"] for a in src_entry.get("artefacts", [])}
            rows.append(
                [src_entry["source"]] + [str(cat_counts.get(c, 0)) for c in all_cats]
            )
        _table(pdf, headers, rows, col_w)
    pdf.ln(4)

    _subsection_title(pdf, "Data Quality Notes per Category")
    ac = p7.get("artefact_coverage", [])
    for entry in ac:
        notes = entry.get("notes", [])
        if notes:
            pdf.set_x(_MARGIN_L)
            pdf.set_font(_FONT, "B", 9)
            pdf.cell(_USABLE_W, 5, _safe(
                entry["category"].replace("_", " ").title()
                + f" ({entry.get('count', 0)} files):"
            ))
            pdf.ln(5)
            for note in notes:
                _bullet(pdf, note)


def _data_quality(pdf: _PDF, p7: dict, state: State) -> None:
    pdf.add_page()
    _section_title(pdf, "6. Data Quality and Anomalies")

    conclusions = p7.get("conclusions", {})
    dq = conclusions.get("data_quality", [])
    _subsection_title(pdf, "Data Quality Observations")
    if dq:
        for item in dq:
            _bullet(pdf, item)
    else:
        _body_text(pdf, "No data quality issues recorded.")
    pdf.ln(4)

    _subsection_title(pdf, "Pipeline Anomaly Flags")
    flags = [f for f in (state.anomaly_flags or []) if f]
    if flags:
        for i, flag in enumerate(flags, 1):
            _numbered(pdf, i, flag)
    else:
        _body_text(pdf, "No anomaly flags recorded.")

    _p5_anomaly_detail(pdf, state)


def _p5_anomaly_detail(pdf: _PDF, state: State) -> None:
    """Render a per-file breakdown of P5 anomaly checks on a new page."""
    p5_anomalies: list[dict] = (
        state.phase_outputs
        .get("p5_normalisation_and_anomaly_checking", {})
        .get("derived_anomalies", [])
    )
    if not p5_anomalies:
        return

    # Row-level check keys whose values are lists of row indices
    _ROW_CHECKS = {
        "timestamp_regression", "timestamp_gap", "zero_coordinate",
        "missing_gps", "coordinate_jump", "altitude_negative",
        "altitude_spike", "motor_airborne_off", "gps_poor_fix",
        "gps_accuracy_poor", "quaternion_invalid", "attitude_out_of_bounds",
        "battery_cell_voltage_out_of_range", "battery_cell_imbalance",
        "battery_temperature_out_of_range", "motor_on_empty_battery",
    }
    # Column-level check keys whose values are lists of column names
    _COL_CHECKS = {"contains_no_value", "contains_constant_value"}

    # Group by evidence_category, preserving SOURCE_IDENTIFICATION_TYPES order
    from config import SOURCE_IDENTIFICATION_TYPES
    cat_order = ["databases", "drone_logs", "flight_logs", "flight_records",
                 "account_data", "images", "videos"]
    by_cat: dict[str, list[dict]] = {}
    for a in p5_anomalies:
        cat = a.get("evidence_category") or "other"
        by_cat.setdefault(cat, []).append(a)

    # Build sha256 → original filename lookup from P3+P4 artefacts so image/video
    # entries can show the real media filename instead of the _exif.json sidecar name.
    p3_arts = state.phase_outputs.get("p3_artefact_extraction", {}).get("extracted_artefacts", [])
    p4_arts = state.phase_outputs.get("p4_decision_and_orchestration", {}).get("decision_and_orchestration_artefacts", [])
    _sha_to_fname: dict[str, str] = {
        a["sha256"]: Path(str(a["stored_path"])).name
        for a in (*p3_arts, *p4_arts)
        if a.get("sha256") and a.get("stored_path")
    }

    pdf.ln(4)
    _subsection_title(pdf, "Artefact-Level Anomaly Detail")
    _body_text(pdf,
        "The following summarises which automated checks fired for each "
        "artefact processed in Phase 5. Row counts indicate affected data rows; "
        "column lists are truncated to five entries."
    )
    pdf.ln(3)

    for cat in cat_order:
        entries = by_cat.get(cat, [])
        if not entries:
            continue

        # Category sub-header
        pdf.set_x(_MARGIN_L)
        pdf.set_font(_FONT, "B", 9)
        pdf.set_fill_color(235, 239, 250)
        pdf.cell(_USABLE_W, 5, _safe(cat.replace("_", " ").title()), fill=True, border=1)
        pdf.ln(6)

        for a in entries:
            # For image/video entries, resolve the original media filename via the
            # evidence_sha256 → P3/P4 artefact lookup; fall back to the sidecar name.
            if cat in ("images", "videos") and a.get("evidence_sha256") in _sha_to_fname:
                fname = _sha_to_fname[a["evidence_sha256"]]
            else:
                fname = Path(str(a.get("stored_path", "-"))).name
            observations: list[dict] = a.get("observations", [])

            # Collect all fired checks across observation dicts
            fired: list[str] = []
            for obs in observations:
                for key, val in obs.items():
                    if key == "database_empty" and val is True:
                        fired.append("database_empty: all tables empty")
                    elif key == "format":
                        entry_count = sum(
                            len(o.get("entries", [])) for o in observations
                        )
                        fired.append(f"format: {val}  |  entries: {entry_count}")
                    elif key == "entries":
                        pass  # handled with "format" above
                    elif key == "exif_zero_date" and val is True:
                        fired.append("exif_zero_date: EXIF timestamp is zeroed or missing")
                    elif key == "exif_missing_gps" and val is True:
                        fired.append("exif_missing_gps: no GPS coordinates in EXIF metadata")
                    elif key in ("norm_date", "norm_time", "gps_latitude", "gps_longitude"):
                        pass  # informational fields, not anomalies
                    elif key in _ROW_CHECKS and isinstance(val, list):
                        fired.append(f"{key}: {len(val)} row(s) affected")
                    elif key in _COL_CHECKS and isinstance(val, list):
                        preview = val[:5]
                        extra = len(val) - 5
                        col_str = ", ".join(preview)
                        if extra > 0:
                            col_str += f"  (+{extra} more)"
                        fired.append(f"{key}: {len(val)} column(s) - {col_str}")

            if not fired:
                continue

            # File name as bold indent label
            pdf.set_x(_MARGIN_L + 4)
            pdf.set_font(_FONT, "B", 8)
            pdf.set_text_color(50, 50, 50)
            pdf.multi_cell(_USABLE_W - 4, _LINE_H, _safe(fname))
            pdf.set_text_color(0, 0, 0)

            for line in fired:
                pdf.set_x(_MARGIN_L + 10)
                pdf.set_font(_FONT, "", 8)
                usable = _USABLE_W - 10
                pdf.cell(4, _LINE_H, "-")
                pdf.multi_cell(usable - 4, _LINE_H, _safe(line))

            pdf.ln(1)

        pdf.ln(2)


def _further_investigation(pdf: _PDF, p7: dict) -> None:
    pdf.add_page()
    _section_title(pdf, "7. Further Investigation Items")
    _body_text(pdf,
        "The following items were identified by automated analysis as requiring "
        "manual investigator follow-up. They represent unresolved questions or "
        "limitations that the pipeline cannot resolve automatically."
    )
    pdf.ln(3)

    conclusions = p7.get("conclusions", {})
    items = conclusions.get("further_investigation", [])
    if not items:
        _body_text(pdf, "No further investigation items identified.")
        return
    for i, item in enumerate(items, 1):
        _numbered(pdf, i, item)


def _appendix_hashes(pdf: _PDF, state: State) -> None:
    pdf.add_page()
    _section_title(pdf, "Appendix A - Extracted Artefact Hash Manifest")
    _body_text(pdf,
        "Each artefact extracted in Phase 3 is listed below with its full "
        "SHA-256 and SHA-1 cryptographic hashes. These values can be used to "
        "independently verify the integrity of every extracted file."
    )
    pdf.ln(2)

    p3_artefacts = (
        state.phase_outputs.get("p3_artefact_extraction", {})
        .get("extracted_artefacts", [])
    )
    if not p3_artefacts:
        _body_text(pdf, "No extracted artefacts recorded.")
        return

    for a in p3_artefacts:
        _hash_block(pdf, a)


def _hash_block(pdf: _PDF, artefact: dict) -> None:
    """Render one artefact as a 3-row block: metadata strip + SHA-256 + SHA-1.

    All rows span the full usable page width (180 mm) so the complete hash
    values are never truncated.
    """
    fname    = Path(str(artefact.get("stored_path", "-"))).name
    category = (artefact.get("artefact_category") or "-").replace("_", " ").title()
    source   = artefact.get("source_identification") or "-"
    method   = artefact.get("acquisition_method") or "-"
    sha256   = artefact.get("sha256") or "not computed"
    sha1     = artefact.get("sha1")   or "not computed"

    # All three rows use the same fixed height so they are visually identical.
    row_h = 5

    # Row 1 — metadata strip (shaded): file | category | source | method
    pdf.set_font(_FONT, "B", 8)
    pdf.set_fill_color(225, 230, 245)
    pdf.cell(62, row_h, _safe(fname[:55]),  border=1, fill=True)
    pdf.cell(40, row_h, _safe(category),   border=1, fill=True)
    pdf.cell(40, row_h, _safe(source),     border=1, fill=True)
    pdf.cell(38, row_h, _safe(method),     border=1, fill=True)
    pdf.ln()

    # Row 2 — SHA-256
    pdf.set_fill_color(250, 250, 252)
    pdf.set_font(_FONT, "B", 7)
    pdf.cell(20, row_h, "SHA-256:", border=1, fill=True)
    pdf.set_font("Courier", "", 7)
    pdf.cell(160, row_h, _safe(sha256), border=1, fill=True)
    pdf.ln()

    # Row 3 — SHA-1
    pdf.set_fill_color(250, 250, 252)
    pdf.set_font(_FONT, "B", 7)
    pdf.cell(20, row_h, "SHA-1:", border=1, fill=True)
    pdf.set_font("Courier", "", 7)
    pdf.cell(160, row_h, _safe(sha1), border=1, fill=True)
    pdf.ln()
    pdf.ln(4)  # inter-block gap


def _appendix_lineage(pdf: _PDF, state: State) -> None:
    pdf.add_page()
    _section_title(pdf, "Appendix B - Evidence Derivation Summary")
    _body_text(pdf,
        "This table summarises how many artefacts were derived at each pipeline "
        "phase, per evidence source and category. It demonstrates the processing "
        "chain from extracted artefacts (P3) through decoded outputs (P4) to "
        "normalised analysis-ready files (P5)."
    )
    pdf.ln(3)

    p3 = state.phase_outputs.get("p3_artefact_extraction", {}).get("extracted_artefacts", [])
    p4 = state.phase_outputs.get("p4_decision_and_orchestration", {}).get("decision_and_orchestration_artefacts", [])
    p5 = state.phase_outputs.get("p5_normalisation_and_anomaly_checking", {}).get("normalised_artefacts", [])

    def _count(artefacts: list, src: str, cat: str) -> int:
        return sum(
            1 for a in artefacts
            if a.get("source_identification") == src
            and a.get("artefact_category") == cat
        )

    sources = [s for s in SOURCE_IDENTIFICATION_TYPES
               if any(a.get("source_identification") == s for a in p3)]

    for src in sources:
        _subsection_title(pdf, src.replace("_", " ").title())
        headers = ["Category", "P3 Extracted", "P4 Decoded", "P5 Normalised"]
        col_w   = [70, 30, 30, 40]
        rows = []
        for cat in CONTROLLER_ARTEFACT_CATEGORIES:
            c3 = _count(p3, src, cat)
            c4 = _count(p4, src, cat)
            c5 = _count(p5, src, cat)
            if c3 or c4 or c5:
                rows.append([cat.replace("_", " ").title(), str(c3), str(c4), str(c5)])
        if rows:
            _table(pdf, headers, rows, col_w)
        else:
            _body_text(pdf, "No artefacts for this source.")
        pdf.ln(4)


def _appendix_tool_log(pdf: _PDF, state: State) -> None:
    pdf.add_page()
    _section_title(pdf, "Appendix C - Tool Invocation Log")
    _body_text(pdf,
        "All external tool invocations executed during this analysis are recorded below, "
        "in chronological order. Each entry includes the timestamp, tool name, version, "
        "return code, full command, and output files produced."
    )
    pdf.ln(2)

    log = state.tool_invocation_log or []
    if not log:
        _body_text(pdf, "No tool invocations recorded.")
        return

    for i, entry in enumerate(log):
        ts      = (entry.get("timestamp") or "")[:19].replace("T", " ")
        tool    = entry.get("tool_name") or "-"
        version = entry.get("version") or "-"
        rc      = entry.get("return_code")
        rc_str  = str(rc) if rc is not None else "n/a"
        args    = entry.get("args") or []
        out     = entry.get("output_paths") or []

        # Command: join args, shorten long absolute paths to filename only for readability
        def _shorten(a: str) -> str:
            p = Path(a)
            return p.name if (len(a) > 40 and p.suffix) else a

        cmd = " ".join(_shorten(str(a)) for a in args)

        # Alternating background
        pdf.set_fill_color(245, 247, 252) if i % 2 == 0 else pdf.set_fill_color(255, 255, 255)

        # Header line: timestamp | tool | version | rc
        pdf.set_x(_MARGIN_L)
        pdf.set_font(_FONT, "B", 8)
        header_text = f"{ts}   {tool}   v{version}   rc={rc_str}"
        pdf.cell(_USABLE_W, 5, _safe(header_text), fill=True)
        pdf.ln(5)

        # Command line
        pdf.set_x(_MARGIN_L + 4)
        pdf.set_font(_FONT, "", 7.5)
        pdf.multi_cell(_USABLE_W - 4, _LINE_H, _safe("cmd: " + cmd[:200]))

        # Output paths (filenames only)
        if out:
            out_str = ", ".join(Path(str(p)).name for p in out[:4])
            if len(out) > 4:
                out_str += f" (+{len(out)-4} more)"
            pdf.set_x(_MARGIN_L + 4)
            pdf.set_font(_FONT, "I", 7.5)
            pdf.multi_cell(_USABLE_W - 4, _LINE_H, _safe("out: " + out_str))

        pdf.ln(2)


def _appendix_tool_overview(pdf: _PDF) -> None:
    pdf.add_page()
    _section_title(pdf, "Appendix D - DFDOF Proof of Concept Overview")

    _body_text(pdf,
        "The Drone Forensic Decision and Orchestration Framework (DFDOF) is an automated "
        "8-phase forensic pipeline for DJI drone evidence. It ingests images of the controller, "
        "drone flight storage and SD cards, then processes them into a structured analysis and report. "
    )
    pdf.ln(3)

    phases = [
        (
            "P1  Provenance and Integrity",
            "Classifies input files (ZIP/E01/.001) by content signatures. Computes SHA-256 "
            "and SHA-1 for all input evidence. Presents a source classification summary for "
            "operator confirmation before processing begins.",
            "Input: evidence directory.  Output: classified evidence objects with hashes.",
        ),
        (
            "P2  Image Parsing",
            "Makes all sources search-ready. Decrypts iOS backups into a domain directory "
            "tree. Extracts Android device metadata (DeviceInfo.xml, ApplicationInfo.xml, "
            "packages.list). Produces backup_info.json with device identifiers and installed "
            "DJI applications.",
            "Input: raw evidence files.  Output: parsed directory structures, backup_info.json.",
        ),
        (
            "P3  Artefact Extraction",
            "Root-driven category extraction. Discovers DJI app roots by bundle-ID segment "
            "matching. Recurses into configured per-platform category paths and filters by "
            "extension. Rejects empty files. Each artefact is wrapped in an Evidence object "
            "with a parent hash linking it to its source.",
            "Input: parsed directories.  Output: categorised artefacts (flight records, drone "
            "logs, flight logs, databases, images, videos, account data).",
        ),
        (
            "P4  Decision and Orchestration",
            "Dispatches each artefact category to the appropriate specialist tool: DatCon "
            "for .DAT drone logs (produces CSV + KML), TXTlogToCSV for flight record .txt "
            "files, ExifTool for images and videos, Python parsers for account data "
            "(.plist/.xml). Computes hashes for all tool outputs.",
            "Input: extracted artefacts.  Output: decoded CSVs, KML files, EXIF JSON, "
            "account data observations.",
        ),
        (
            "P5  Normalisation and Anomaly Checking",
            "Normalises all CSVs to UTC timestamps and a unified schema. Applies 9 shared "
            "telemetry anomaly checks (timestamp regression/gaps, zero coordinates, GPS "
            "quality, altitude spikes, motor-airborne-off) plus format-specific checks for "
            "flight records (battery voltage, temperature) and drone logs (quaternion, hDOP). "
            "Detects empty databases, unreadable flight logs, and zeroed EXIF timestamps.",
            "Input: decoded artefacts.  Output: normalised CSVs, anomaly observations.",
        ),
        (
            "P6  Multi-Source Correlation",
            "Correlates flight records with drone logs using two criteria: "
            "(1) temporal overlap >= 60 s AND >= 90% of the shorter flight's duration; "
            "(2) median haversine distance of nearest-neighbour GPS pairs <= 25 m with >= 5 matched pairs. "
            "Deduplicates FR candidates when multiple apps recorded the same flight. Builds a unified "
            "per-flight event timeline from all matched sources. Also correlates media files by EXIF "
            "timestamp, GPS bounding box, and video duration. "
            "In the correlation summary: Overlap is the temporal overlap as a percentage of the shorter "
            "flight's duration; GPS Match Rate is the fraction of flight-record GPS rows that found a "
            "spatially matched drone-log row within a +-2 s window.",
            "Input: normalised CSVs.  Output: timeline_flightXX.json per flight.",
        ),
        (
            "P7  Analysis and Validation",
            "Aggregates results from all prior phases into a structured analysis. Resolves "
            "device identity (drone serial, model, app version, account email) across sources "
            "with confidence levels (single-source / multi-source / inconsistent). Computes "
            "per-flight metrics (peak height, media capture, record completeness). Produces "
            "coverage scores and a grouped conclusions structure with a dedicated "
            "further_investigation section.",
            "Input: all phase outputs.  Output: analysis dict with conclusions in state.json.",
        ),
        (
            "P8  Automated Reporting",
            "Generates this PDF forensic baseline report from all prior phase outputs. "
            "Produces sensor telemetry plots (altitude, speed, attitude, battery, GPS) from "
            "normalised CSVs, a dual-source flight track plot, and the structured appendices. "
            "All figures are also saved as standalone PNG files.",
            "Input: state.json (all phase outputs).  Output: PDF report + PNG plot files.",
        ),
    ]

    for title, description, io in phases:
        # Phase title bar
        pdf.set_font(_FONT, "B", 9)
        pdf.set_fill_color(215, 222, 240)
        pdf.cell(0, 6, _safe(title), fill=True, border=1)
        pdf.ln(6)
        # Description
        pdf.set_x(_MARGIN_L)
        pdf.set_font(_FONT, "", 8.5)
        pdf.multi_cell(_USABLE_W, _LINE_H, _safe(description))
        # I/O line
        pdf.set_x(_MARGIN_L)
        pdf.set_font(_FONT, "I", 7.5)
        pdf.set_text_color(80, 80, 80)
        pdf.multi_cell(_USABLE_W, _LINE_H, _safe(io))
        pdf.set_text_color(0, 0, 0)
        pdf.ln(3)

    pdf.ln(2)
    _subsection_title(pdf, "Disclaimer")
    pdf.set_x(_MARGIN_L)
    pdf.set_font(_FONT, "", 8.5)
    pdf.multi_cell(_USABLE_W, _LINE_H, _safe(
        "DFDOF was developed by Floris Krijger, MSc Security and Network Engineering, "
        "University of Amsterdam, as a Master's thesis project (1 April 2026 - 30 June 2026). "
        "This proof of concept has been developed and tested on a targeted subset of the NIST VTO "
        " forensic drone dataset and is not a finished, production-ready system. Before use in "
        "any operational or legal context, further testing, validation across additional drone "
        "models and evidence types, and robustness improvements are required. The authors "
        "accept no liability for conclusions drawn from automated pipeline output without "
        "independent expert verification."
    ))


# Helpers

def _find_kml_path(state: State) -> Path | None:
    for entry in state.tool_invocation_log:
        if entry.get("tool_name") == "datcon":
            for p in (entry.get("output_paths") or []):
                if str(p).lower().endswith(".kml"):
                    return Path(p)
    return None


def _flight_csv_paths(
    state: State, flight: dict
) -> tuple[Path | None, Path | None]:
    p5_artefacts = (
        state.phase_outputs
        .get("p5_normalisation_and_anomaly_checking", {})
        .get("normalised_artefacts", [])
    )
    sha_to_norm = {a.get("sha256", ""): a for a in p5_artefacts}

    fr_csv: Path | None = None
    dl_csv: Path | None = None
    for seg in flight.get("flights_identified", []):
        a = sha_to_norm.get(seg.get("evidence_sha256", ""))
        if not a:
            continue
        sp = a.get("stored_path")
        if not sp:
            continue
        p = Path(sp)
        if not p.exists():
            continue
        cat = a.get("artefact_category")
        if cat == FLIGHT_RECORDS:
            fr_csv = p
        elif cat == DRONE_LOGS:
            dl_csv = p
    return fr_csv, dl_csv


def _load_timeline_events(tl_path: str) -> list[dict]:
    if not tl_path:
        return []
    try:
        tl = json.loads(Path(tl_path).read_text(encoding="utf-8"))
        return tl.get("events", [])
    except Exception:
        return []


def _event_detail(ev: dict) -> str:
    data  = ev.get("data", {})
    event = ev.get("event", "")
    if event == "Log started":
        parts = []
        if data.get("serial_drone"):
            parts.append(f"SN: {data['serial_drone']}")
        if data.get("dji_app_version"):
            parts.append(f"App: {data['dji_app_version']}")
        if data.get("name_drone"):
            parts.append(data["name_drone"])
        return "; ".join(parts)[:80]
    if event == "Log ended":
        parts = []
        if data.get("distance_to_homepoint") is not None:
            parts.append(f"Dist home: {data['distance_to_homepoint']:.1f} m")
        if data.get("height") is not None:
            parts.append(f"Height: {data['height']:.1f} m")
        if data.get("duration_recording") is not None:
            parts.append(f"Rec: {data['duration_recording']} s")
        return "; ".join(parts)[:80]
    if event == "Reached peak height":
        h = data.get("relative_height")
        return f"{h:.1f} m" if h is not None else "-"
    if event in ("Record mode changed", "Photo mode changed"):
        mode = data.get("record_mode") or data.get("photo_mode") or "-"
        return str(mode)[:40]
    if "motor_state" in data:
        return data["motor_state"]
    return ""


def _short_source(source: str) -> str:
    return (source
            .replace("controller_ios", "ctrl_ios")
            .replace("controller_android", "ctrl_and")
            .replace("flight_records", "fr")
            .replace("drone_logs", "dl"))[:28]


def _embed_image(pdf: _PDF, path: Path, w: int = 160) -> None:
    try:
        x = (_PAGE_W - w) / 2
        pdf.image(str(path), x=x, w=w)
    except Exception:
        _body_text(pdf, f"[Image could not be embedded: {path.name}]")


# Generic PDF primitives

def _section_title(pdf: _PDF, text: str) -> None:
    pdf.set_font(_FONT, "B", 12)
    pdf.set_fill_color(220, 228, 245)
    pdf.cell(0, 7, _safe(text), fill=True)
    pdf.ln(11)


def _subsection_title(pdf: _PDF, text: str) -> None:
    pdf.set_font(_FONT, "B", 10)
    pdf.cell(0, 5, _safe(text))
    pdf.ln(6)


def _body_text(pdf: _PDF, text: str) -> None:
    pdf.set_x(_MARGIN_L)
    pdf.set_font(_FONT, "", 9)
    pdf.multi_cell(_USABLE_W, _LINE_H, _safe(text))
    pdf.ln(1)


def _bullet(pdf: _PDF, text: str, indent: int = 5) -> None:
    pdf.set_x(_MARGIN_L)
    usable = _USABLE_W - indent
    pdf.set_font(_FONT, "", 9)
    pdf.cell(indent, _LINE_H, "-")
    pdf.multi_cell(usable, _LINE_H, _safe(text))


def _numbered(pdf: _PDF, n: int, text: str, indent: int = 7) -> None:
    pdf.set_x(_MARGIN_L)
    usable = _USABLE_W - indent
    pdf.set_font(_FONT, "", 9)
    pdf.cell(indent, _LINE_H, f"{n}.")
    pdf.multi_cell(usable, _LINE_H, _safe(text))


_KV_KEY_W = 52

def _kv(pdf: _PDF, key: str, value: str) -> None:
    pdf.set_x(_MARGIN_L)
    val_w = _USABLE_W - _KV_KEY_W
    pdf.set_font(_FONT, "B", 9)
    pdf.cell(_KV_KEY_W, _LINE_H, _safe(key + ":"))
    pdf.set_font(_FONT, "", 9)
    pdf.multi_cell(val_w, _LINE_H, _safe(str(value)))


def _kv_hash(pdf: _PDF, key: str, value: str) -> None:
    """Like _kv but renders the value in Courier 7pt so a full 64-char hash fits."""
    pdf.set_x(_MARGIN_L)
    val_w = _USABLE_W - _KV_KEY_W
    pdf.set_font(_FONT, "B", 9)
    pdf.cell(_KV_KEY_W, _LINE_H, _safe(key + ":"))
    pdf.set_font("Courier", "", 7)
    pdf.multi_cell(val_w, _LINE_H, _safe(str(value)))


def _format_basis(data: dict) -> str:
    if "video_duration_s" in data:
        return (
            f"Video duration {data['video_duration_s']} s matches "
            f"log recording {data['log_duration_s']} s"
        )
    if "entry_count" in data:
        return (
            f"Log messages match ({data['entry_count']} entries, "
            f"format: {data.get('format', '?')})"
        )
    if "latitude" in data:
        return (
            f"GPS within flight bounding box "
            f"(lat {float(data['latitude']):.4f}, "
            f"lon {float(data['longitude']):.4f})"
        )
    return str(data)


def _corr_row(
    pdf: _PDF,
    cells: list[str],
    col_widths: list[int],
    fill_rgb: tuple[int, int, int],
    *,
    text_rgb: tuple[int, int, int] = (0, 0, 0),
    bold: bool = False,
) -> None:
    base_h = 5
    line_counts = [c.count("\n") + 1 for c in cells]
    row_h = max(line_counts) * base_h
    padded = [c + "\n" * (max(line_counts) - c.count("\n") - 1) for c in cells]
    y0 = pdf.get_y()
    pdf.set_fill_color(*fill_rgb)
    pdf.set_xy(_MARGIN_L, y0)
    for w in col_widths:
        pdf.cell(w, row_h, "", border=1, fill=True)
    pdf.set_font(_FONT, "B" if bold else "", 8)
    pdf.set_text_color(*text_rgb)
    x = _MARGIN_L
    for text, w in zip(padded, col_widths):
        pdf.set_xy(x, y0)
        pdf.multi_cell(w, base_h, text, border=0, fill=False, new_x="RIGHT", new_y="TOP")
        x += w
    pdf.set_xy(_MARGIN_L, y0 + row_h)
    pdf.set_text_color(0, 0, 0)


def _table(
    pdf: _PDF,
    headers: list[str],
    rows: list[list[str]],
    col_widths: list[int],
) -> None:
    base_h   = 5
    header_h = base_h + 1
    page_bottom = pdf.h - pdf.b_margin  # usable bottom y

    def _draw_header() -> None:
        pdf.set_font(_FONT, "B", 8)
        pdf.set_fill_color(50, 80, 130)
        pdf.set_text_color(255, 255, 255)
        for header, w in zip(headers, col_widths):
            pdf.cell(w, header_h, _safe(header), border=1, fill=True)
        pdf.ln()
        pdf.set_text_color(0, 0, 0)

    _draw_header()

    pdf.set_font(_FONT, "", 8)
    for i, row in enumerate(rows):
        fill_color = (245, 247, 252) if i % 2 == 0 else (255, 255, 255)

        cells     = [_safe(str(c)) for c in row]
        max_lines = max(
            len(list(pdf.multi_cell(w, base_h, c, dry_run=True, output="LINES")))  # type: ignore[arg-type]
            for c, w in zip(cells, col_widths)
        )
        row_h = max_lines * base_h

        # If this row would overflow, start a new page and repeat the header.
        if pdf.get_y() + row_h > page_bottom:
            pdf.add_page()
            _draw_header()
            pdf.set_font(_FONT, "", 8)

        y0 = pdf.get_y()

        # Draw fill and border rectangles at the exact row height for every cell.
        # This guarantees uniform cell borders regardless of how many lines each
        # cell's text occupies, avoiding gaps when cells in the same row differ.
        pdf.set_fill_color(*fill_color)
        x = _MARGIN_L
        for w in col_widths:
            pdf.rect(x, y0, w, row_h, style="DF")
            x += w

        # Overlay text without fill or border (auto page-break disabled for rect rows).
        x = _MARGIN_L
        for cell_text, w in zip(cells, col_widths):
            pdf.set_xy(x, y0)
            pdf.multi_cell(w, base_h, cell_text, border=0, fill=False,
                           new_x="RIGHT", new_y="TOP")
            x += w

        pdf.set_xy(_MARGIN_L, y0 + row_h)
    pdf.set_fill_color(255, 255, 255)


def _format_size(n_bytes: int) -> str:
    if n_bytes == 0:
        return "0 B"
    units = ["B", "KB", "MB", "GB", "TB"]
    i = min(int(math.log(n_bytes, 1024)), len(units) - 1)
    return f"{n_bytes / (1024 ** i):.1f} {units[i]}"


def _confidence_badge(confidence: str) -> str:
    badges = {
        "multi-source":  "[M] Multi-source",
        "single-source": "[S] Single-source",
        "inconsistent":  "[!] Inconsistent",
    }
    return badges.get(confidence, confidence)


def _status_badge(status: str) -> str:
    badges = {"ok": "[OK]", "partial": "[~] Partial", "failed": "[X] Failed"}
    return badges.get(status, status)


def _safe(text: str) -> str:
    """Normalise typographic characters then replace anything outside latin-1."""
    text = (
        text
        .replace("—", "-")   # em-dash
        .replace("–", "-")   # en-dash
        .replace("‘", "'")   # left single quote
        .replace("’", "'")   # right single quote
        .replace("“", '"')   # left double quote
        .replace("”", '"')   # right double quote
        .replace(" ", " ")   # non-breaking space
        .replace("�", "?")   # replacement character (keep as literal ?)
    )
    return text.encode("latin-1", errors="replace").decode("latin-1")
